FROM node:16-alpine3.11

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
COPY . .

# If you are building your code for production
# RUN npm ci --omit=dev

# Bundle app source

EXPOSE 8080
CMD [ "npm", "start" ]