version: '3'
services:
  api:
    build: ./api
    command: npm run start
    ports: 
      - "80:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.prod
    container_name: realworld-docker-frontent
    command: npm run serve
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
volumes:
  mongodb_api:
