version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api/src:/usr/src/app/src
    command: npm run dev
    ports: 
      - "80:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
volumes:
  mongodb_api:
