version: '3'
services:
  api:
    build: ./api
    volumes:
      - ./api/src:/usr/src/app/src
    command: npm run dev
    environment:
      - PORT=3001
      - HOST=0.0.0.0
      - MONGO_URL=mongodb://api_db:27017/api
    depends_on:
      - api_db
  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    container_name: realworld-docker-frontent
    command: npm run start
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - api
  nginx:
    image: nginx:1-alpine
    container_name: websystem-docker-demo-nginx
    ports:
     - "80:80"
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
      - frontend
  api_db:
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db
volumes:
  mongodb_api:
